# netlify.toml
[build]
  base = "pokeliquid"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
